jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      # ... other steps

      - name: Publish Project 1 to Chromatic
        uses: chromaui/action@latest
        with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: chpt_19ae80df1c9580a
          workingDir: packages/components/button
          onlyChanged: true # 👈 Required option to enable TurboSnap